// AI Startups Job Board Data
// Source: a16z AI Application Spending Report
// Data collected: February 2026

const jobsData = [
    {
        name: "OpenAI",
        website: "https://openai.com/careers/",
        jobs: [
            "Account Director, Digital Native",
            "Account Director, Digital Native Core",
            "Account Director, Digital Native Large Enterprise",
            "Account Director, Digital Native New Business",
            "Account Director, Digital Natives",
            "Account Director, Digital Natives - Land team",
            "Account Director, Digital Natives - Land Team",
            "Account Director, Education",
            "Account Director, Enterprise",
            "Account Director, Federal Civilian",
            "Account Director, Federal Partnerships",
            "Account Director, Financial Services",
            "Account Director, Healthcare & Life Sciences",
            "Account Director, Large Enterprise",
            "Account Director, Large Enterprise (Southeast Asia)",
            "Account Director, Mid-Market",
            "Account Director, Mid-Market Enterprise",
            "Account Director, Retail",
            "Account Director, Startups Expansion",
            "Account Director, Startups | India",
            "Account Director, Startups New Business",
            "Account Director - Tokyo",
            "Administrative Business Partner, Global Affairs",
            "Administrative Business Partner (Technical Leadership Support)",
            "AI Deployment Engineer",
            "AI Deployment Engineer- ChatGPT Ecosystem",
            "AI Deployment Engineer- Codex",
            "AI Deployment Engineer, Gov",
            "AI Deployment Engineer- Media Partnerships",
            "AI Deployment Engineer- Startups",
            "AI Deployment Manager - NYC",
            "AI Deployment Manager - San Francisco",
            "AI Deployment Manager - Singapore",
            "AI Deployment Manager - US Remote",
            "AI Success Engineer",
            "AI Success Engineer | DACH",
            "AI Success Engineer - EDU",
            "AI Success Engineer - India",
            "AI Success Engineer - NYC",
            "AI Success Engineer - San Francisco",
            "AI Success Engineer - São Paulo, Brazil",
            "AI Success Engineer - Singapore",
            "AI Success Engineer - Tokyo",
            "AI Success Engineer - US Remote",
            "AI Support Engineer - Dublin",
            "AI Support Engineer - San Francisco",
            "AI Support Engineer - Singapore",
            "AI Support Engineer - Tokyo",
            "Analytics Engineer",
            "Analytics Engineer, Finance",
            "Android Engineer, Applied Foundations",
            "Android Engineer, ChatGPT Enginnering",
            "Applied Data Science & Machine Learning Leader - Global Forecasting",
            "Applied Data Scientist, Unit Economics Understanding",
            "Art Director, Creative Studio",
            "ASIC Firmware Engineer, Modeling",
            "Associate General Counsel, Japan",
            "Associate General Counsel, Policy (LATAM)",
            "AudioVisual Deployment Engineer",
            "B2B Strategic Finance",
            "Backend Engineer, Consumer Products",
            "Backend Software Engineer - B2B Applications",
            "Backend Software Engineer, ChatGPT Engineering",
            "Backend Software Engineer (Evals)",
            "Backend Software Engineer, Growth",
            "Backend Software Engineer, GTM Innovation",
            "Brand Designer",
            "Business Communications Lead, APAC",
            "Camera Firmware Engineer, Consumer Products",
            "Camera ISP Software Engineer, Consumer Products",
            "Client Platform Engineer",
            "Compute Business Operations Lead",
            "Compute Infrastructure Strategy Lead",
            "Connectivity Software Engineer",
            "Content Designer",
            "Content Integrity Analyst",
            "Copywriter, Creative Studio",
            "Corporate Development, Strategy & Scouting Lead",
            "Corporate Finance Manager",
            "Corporate Security Manager, Global Design & Construction",
            "Corporate Security Operations Manager, Tokyo",
            "Counsel, Corporate",
            "Creative Director, International",
            "Datacenter Hardware Operations Technician, AI Compute Infrastructure - Stargate",
            "Datacenter Networking Technician, AI Compute Deployment - Stargate",
            "Data Engineer, Analytics",
            "Data Science Manager, Integrity",
            "Data Scientist",
            "Data Scientist, Codex",
            "Data Scientist, Financial Engineering",
            "Data Scientist, Infrastructure",
            "Data Scientist, Integrity",
            "Data Scientist, Marketing",
            "Data Scientist, Platform and B2B Products",
            "Data Scientist, Product",
            "Data Scientist, Strategic Intelligence & Risk",
            "Data Scientist, User Operations",
            "Deal Desk Sr. Lead",
            "Deal Lead, Special Situtations",
            "Design Verification Engineer",
            "Developer Experience Engineer",
            "Developer Product Communications Lead",
            "Digital Natives Sales Manager, APAC",
            "Director of Data Engineering and Agentic AI Automation, Finance",
            "Director of Strategic Finance, Payments & Platform",
            "Director, People Operations",
            "Distributed Training Engineer, Sora",
            "Electrical Engineer - Systems",
            "Embedded SWE, Consumer Products",
            "Employment Investigator",
            "Engineering Manager, Answer Experience",
            "Engineering Manager, API Experience",
            "Engineering Manager, Atlas",
            "Engineering Manager, Business Growth (ChatGPT)",
            "Engineering Manager, Cloud Infrastructure Automation",
            "Engineering Manager, Core Services",
            "Engineering Manager, Enterprise Ecosystem",
            "Engineering Manager, Identity Infrastructure",
            "Engineering Manager, Multimodal (API)",
            "Enterprise Security Engineer",
            "Executive Business Partner",
            "Executive Business Partner, Revenue",
            "Executive Business Partner (Technical VP Support)",
            "Executive, Strategic Global Partnerships & Ecosystem",
            "Facilities Standards & Strategy, Program Manager",
            "Forward Deployed Engineer - Dublin",
            "Forward Deployed Engineer (FDE), Financial Services - NYC",
            "Forward Deployed Engineer (FDE), Life Sciences - Dublin",
            "Forward Deployed Engineer (FDE), Life Sciences - London",
            "Forward Deployed Engineer (FDE), Life Sciences - Munich",
            "Forward Deployed Engineer (FDE), Life Sciences - NYC",
            "Forward Deployed Engineer (FDE), Life Sciences - Paris",
            "Forward Deployed Engineer (FDE), Life Sciences - SF",
            "Forward Deployed Engineer (FDE) - NYC",
            "Forward Deployed Engineer (FDE) - SF",
            "Forward Deployed Engineer, Gov",
            "Forward Deployed Engineer - London",
            "Forward Deployed Engineer - Munich",
            "Forward Deployed Engineer - Paris",
            "Forward Deployed Engineer - Singapore",
            "Forward Deployed Engineer - Tokyo",
            "Forward Deployed Software Engineer - Dublin",
            "Forward Deployed Software Engineer - London",
            "Forward Deployed Software Engineer - Munich",
            "Forward Deployed Software Engineer - NYC",
            "Forward Deployed Software Engineer - Paris",
            "Forward Deployed Software Engineer - SF",
            "Forward Deployed Software Engineer - Singapore",
            "Forward Deployed Software Engineer - Tokyo",
            "Fraud & Risk Analyst",
            "Frontend Engineer, Dotcom (Marketing)",
            "Frontend Engineer, Financial Web Platform",
            "Frontend Software Engineer - B2B Applications",
            "Full-Stack Engineer, Consumer Products",
            "Full Stack Engineer, Fleet Scheduling",
            "Full Stack Engineer, Health AI",
            "Fullstack Engineer, Intelligence Systems",
            "Fullstack Engineer, Safety Engineering",
            "Full Stack Software Engineer, B2B Applications",
            "Full Stack Software Engineer, ChatGPT Engineering",
            "Full Stack Software Engineer - Enterprise Agents",
            "Full-Stack Software Engineer, Frontier Exploration",
            "Full Stack Software Engineer, Growth",
            "Full Stack Software Engineer, GTM Innovation",
            "Full-Stack SWE, Data Acquisition (Foundations)",
            "Global Business Insights & Automation Lead",
            "Global Payroll Operations Lead",
            "Global Safety Response Operations Analyst",
            "Government Account Director, Defense",
            "Growth - Emails, Notifications and Lifecycle",
            "Growth Lead, India",
            "Growth Lead, Korea",
            "Growth - Performance Marketing & Growth Optimizations",
            "GTM Enablement Manager - Onboarding",
            "Hardware Procurement Operations Lead (Controls & Integrations)",
            "Hardware Regulatory & Compliance Engineer",
            "Head of Business Communications",
            "Head of Data Science and Machine Learning, Global Forecasting",
            "Head of Infrastructure Communications",
            "Head of Operations and Strategy",
            "Head of Sales Development",
            "Head of Sales Enablement",
            "Head of Sales Industries",
            "Head of Tax Policy and Strategic Projects",
            "Head of Trade Compliance & Operations",
            "HPC Systems Engineer, Consumer Products",
            "Inference Technical Lead, Sora",
            "Infrastructure Engineering Lead, IT",
            "iOS Engineer, Applied Foundations",
            "iOS Software Engineer, ChatGPT Engineering",
            "IT Support Specialist",
            "Launch Manager, Certifications",
            "L&D Specialist, Manager Development",
            "Lead Comp Partner EMEA",
            "Lead Product Designer, Health AI",
            "Leave & Accommodation Case Manager",
            "Linux Kernels Software Lead",
            "Machine Learning Data Scientist, Forecasting",
            "M&A Finance Integration Lead",
            "Manager, AI Deployment Engineering",
            "Manager, AI Success Engineers",
            "Manager, Forward Deployed Engineering",
            "Manager, Protection Scientist Engineer, Intelligence and Investigations",
            "Manager, Solutions Engineering - Australia & New Zealand",
            "Marketing & Creative Operations Lead, International",
            "Mechanical Engineer, Hardware Systems",
            "Media Relations, Safety Communications",
            "Mid-Market Enterprise Sales Manager",
            "ML Research Engineer - Hardware Codesign",
            "Model Policy Manager",
            "Motion Designer",
            "Networking Operating System Firmware Engineer",
            "Network Security Engineer",
            "Offensive Security Engineer, Agent Security",
            "Offensive Security Engineer, Hardware",
            "Operations Program Manager, AI Infrastructure",
            "Partner AI Deployment Engineer",
            "Partner Director, Global Accenture Alliance",
            "Partner Director, SMB Partnerships",
            "People Data Automation Analyst",
            "People Systems Analyst (Core - Absence)",
            "Physical Design Engineer",
            "Physical Security Systems Administrator",
            "Physical Security Systems Design Engineer",
            "PM - Finance Transformation",
            "Power Architect",
            "Principal Software Engineer, ChatGPT for Work",
            "Private Equity Partnerships Manager",
            "Product Designer, Business Products",
            "Product Designer, ChatGPT",
            "Product Designer, Growth",
            "Product Engagement Specialist",
            "Product Engineer, GTM Innovation",
            "Product Engineer, Marketing Innovation",
            "Product Manager, API Model Behavior",
            "Product Manager, ChatGPT Business Growth",
            "Product Manager, Codex",
            "Product Manager, Countries & Governments",
            "Product Manager, Integrity",
            "Product Manager, IT",
            "Product Manager, Model Behavior",
            "Product Manager, Private Computing & Encryption",
            "Product Manager, Safety Systems",
            "Product Marketing Manager ChatGPT, Campaigns",
            "Product Partnerships Lead, India",
            "Product Partnerships Lead, Japan",
            "Product Policy - Data Scientist",
            "Product Policy –Policy Manager (Child Safety)",
            "Product & Solutions Lead, Safety and Security",
            "Program Manager",
            "Program Manager, Human Data",
            "Program Manager, Human Data -Strategic Initiatives",
            "Protection Scientist Engineer, Intelligence and Investigations",
            "QA Software Engineer, Consumer Products",
            "Quantitative Intelligence Analyst",
            "Quantitative UX Researcher, Product Policy",
            "Recruiting Manager, Applied AI Engineering",
            "Recruiting Manager, Go To Market & Sales",
            "Regulatory Operations Analyst",
            "Release Engineer, Consumer Products",
            "Reliability/DFX Engineer",
            "Research Engineer",
            "Research Engineer, AI for Science",
            "Research Engineer, Applied AI Engineering",
            "Research Engineer, Codex",
            "Research Engineer, Frontier Evals & Environments",
            "Research Engineer, Frontier Evals & Environments - Finance",
            "Research Engineer, Human-Centered AI",
            "Research Engineer, Human Data",
            "Research Engineer, Monetization AI/ML (SF)",
            "Research Engineer, Notifications",
            "Research Engineer, Privacy",
            "Research Engineer / Research Scientist - Foundations Retrieval Lead",
            "Research Engineer / Research Scientist, Post-Training",
            "Research Engineer/Research Scientist, RL/Reasoning",
            "Research Engineer, Retrieval & Search, Applied Engineering",
            "Research Engineer/Scientist - Generative UI, Consumer Products",
            "Researcher, Alignment",
            "Researcher, Health AI",
            "Researcher, Interpretability",
            "Researcher, Misalignment Research",
            "Researcher, Preparedness",
            "Researcher, Pretraining Safety",
            "Researcher, Robustness & Safety Training",
            "Researcher, Safety Oversight",
            "Researcher, Synthetic RL",
            "Researcher, Training",
            "Researcher, Trustworthy AI",
            "Research Lead, Chemical & Biological Risk",
            "Research Lead, Cyber",
            "Research Scientist",
            "Research Scientist, Mathematical Sciences",
            "Robotics Software Engineer",
            "RTL & Codesign Engineer",
            "RTL & Co-design Engineer (junior)",
            "Safety Response Operations Lead",
            "Salesforce Engineer (GTM Systems)",
            "Sales Lead, Korea",
            "Sales Strategy & Operations - Government and Education",
            "Security Engineer, Agent Security",
            "Security Engineer, Application Security",
            "Security Engineer, Detection and Response",
            "Security Engineer, Infrastructure Security",
            "Security Engineer, Insider Threat Detection & Response",
            "Security Researcher, Trusted Computing and Cryptography",
            "Security Solutions Engineer, Pre-Sales (Security Specialist) - APAC",
            "Senior Counsel, India",
            "Senior Counsel, Litigation",
            "Senior Counsel, Litigation & Regulatory",
            "Senior Counsel, Product (Hardware)",
            "Senior Employment Investigator",
            "Senior IT Support Specialist",
            "Senior Manager, CapEx Accounting",
            "Senior Manager, Supply Chain Business Process Architect",
            "Senior Research Engineer/Scientist - Edge, Consumer Products",
            "Senior Software Engineer, Data Acquisition",
            "Senior Software Engineer, Identity Platform",
            "Senior Support Engineer - Dublin",
            "Senior Support Engineer - Tokyo",
            "Senior Technical Sourcer, Scaling",
            "Signal Integrity Engineer",
            "Simulation Environments Engineer",
            "Simulation Realism Engineer",
            "Site Reliability Engineer, Frontier Systems Infrastructure",
            "SMS Prototype Handling Specialist",
            "Software Engineer",
            "Software Engineer, Accelerators",
            "Software Engineer, Ads Integrity",
            "Software Engineer, Agent Infrastructure",
            "Software Engineer, AI Safety",
            "Software Engineer, API Engineer",
            "Software Engineer, Applied Evals",
            "Software Engineer, Applied Foundations - London",
            "Software Engineer, Backend",
            "Software Engineer, Backend (Knowledge Innovation)",
            "Software Engineer, Backend - Sora",
            "Software Engineer, Caching Infrastructure",
            "Software Engineer, Cloud Infrastructure",
            "Software Engineer, Codex Cloud",
            "Software Engineer, Codex for Teams",
            "Software Engineer, Collective Communication",
            "Software Engineer, Compute - Storage",
            "Software Engineer, Core Services",
            "Software Engineer, Data Acquisition",
            "Software Engineer, Database Systems",
            "Software Engineer, Data Infrastructure",
            "Software Engineer, Data Infrastructure - Research",
            "Software Engineer, Data Visualization",
            "Software Engineer, Developer Productivity",
            "Software Engineer, Distributed Data Systems (Sora)",
            "Software Engineer, Distributed Systems",
            "Software Engineer, Encryption",
            "Software Engineer, Enterprise AI Platform",
            "Software Engineer, Enterprise Identity",
            "Software Engineer, Financial Engineering",
            "Software Engineer, Fleet Hardware Health",
            "Software Engineer, Fleet Management",
            "Software Engineer, Frontier Clusters Infrastructure",
            "Software Engineer, Frontier Systems",
            "Software Engineer, Frontier Systems - Power Management",
            "Software Engineer, Full-Stack — Developer Experience",
            "Software Engineer, Full Stack (Knowledge Innovation)",
            "Software Engineer, Full Stack (People Innovation)",
            "Software Engineer, Full Stack, Revenue Platform",
            "Software Engineer, Gov",
            "Software Engineer, GPU Infrastructure",
            "Software Engineer, GPU Infrastructure - HPC",
            "Software Engineer, Hardware",
            "Software Engineer, Inference – AMD GPU Enablement",
            "Software Engineer, Inference - Multi Modal",
            "Software Engineer, Infrastructure - Analytics",
            "Software Engineer, Infrastructure Reliability",
            "Software Engineer, Infrastructure Security",
            "Software Engineer, Integrity Foundations",
            "Software Engineer, Internal Applications - Enterprise",
            "Software Engineer Internship / Co-op, Applied Emerging Talent (Fall 2026)",
            "Software Engineer - Jobs Platform & Certifications",
            "Software Engineer, Load Balancing - Inference",
            "Software Engineer, Model Inference",
            "Software Engineer, Monetization AI/ML (SF/Seattle)",
            "Software Engineer, Monetization Infrastructure (SF/Seattle)",
            "Software Engineer, Monetization Product & Platform (SF/Seattle)",
            "Software Engineer, Networking - Inference",
            "Software Engineer, Online Storage",
            "Software Engineer, Payments",
            "Software Engineer, Platform Systems",
            "Software Engineer, Privacy",
            "Software Engineer - Privacy & Compliance",
            "Software Engineer, Privacy Infrastructure",
            "Software Engineer, Private Computing",
            "Software Engineer, Productivity",
            "Software Engineer, Real Time",
            "Software Engineer, Reliability",
            "Software Engineer, Research Developer Productivity",
            "Software Engineer, Research - Human Data",
            "Software Engineer, Research Infrastructure",
            "Software Engineer, Scaled Abuse",
            "Software Engineer, Security Observability",
            "Software Engineer - Sensing, Consumer Products",
            "Software Engineer, Triton Compiler",
            "Software Engineer, Trusted Computing and Cryptography",
            "Software Engineer, Youth Well-Being",
            "Solution Engineer | DACH",
            "Solutions Engineer",
            "Solutions Engineering Manager | EMEA",
            "Solutions Engineer, Pre-Sales",
            "Solutions Engineer, Pre-Sales - Tokyo",
            "Solutions Engineer, Public Sector",
            "Solutions Engineer- Startups",
            "Sr. Employee Relations Partner (Non-Investigations)",
            "Sr. HR Business Partner",
            "Strategic Finance, B2B Transactions Lead",
            "Strategic Finance, Compute",
            "Strategic Finance, Hardware Financial Consolidations & Systems",
            "Strategic Finance, Hardware R&D Finance Manager",
            "Strategic Finance Lead, Robotics Hardware",
            "Strategic Sourcing - HD/Research Services",
            "Strategic Sourcing & Partnerships - Software Tools & Licenses",
            "Support Delivery Lead, EMEA - Dublin",
            "Support Delivery Lead, EMEA - London",
            "Support Partner Manager",
            "Support Systems Architect",
            "System Software Engineer, Applied Foundations",
            "System Software Engineer, Consumer Products",
            "Technical Business Development Manager – Infrastructure",
            "Technical Deployment Lead, Financial Services",
            "Technical Deployment Lead, Forward Deployed Engineering - Tokyo",
            "Technical Lead, Safety Research",
            "Technical Program Manager – Adversarial Model Research",
            "Technical Program Manager, Applied Research",
            "Technical Program Manager, Hardware Systems",
            "Technical Program Manager, Human Data",
            "Technical Program Manager, Knowledge Innovation",
            "Technical Program Manager, Partnership Site Deployment - Stargate",
            "Technical Program Manager, Synthetic Data",
            "Technical Program Manager, Trustworthy AI",
            "Thermal Engineer",
            "Third Party Risk Senior Manager, APAC",
            "TLM, Machine Learning, Integrity",
            "Trade Compliance Specialist",
            "Training: ML Framework Engineer",
            "Training Performance Engineer",
            "Trust & Safety Operations Analyst",
            "US Benefits Analyst",
            "User Safety & Risk Operations Manager, Ops Enablement & Analytics",
            "Value Engineering Lead, AI Deployment and Adoption",
            "Vendor Security Program Manager",
            "Vertical Marketing Lead",
            "Workplace Business Partner"
        ]
    },
    {
        name: "Anthropic",
        website: "https://www.anthropic.com/careers",
        jobs: [
            "Geopolitics Analyst, Policy",
            "Manager, National Security Policy",
            "Product Public Policy Manager, Privacy & Data Governance",
            "Public Policy, Events Lead",
            "Regional State and Local Affairs Lead, Midwestern States",
            "Regional State and Local Affairs Lead, Northeast States",
            "Regional State and Local Affairs Lead, Southern States",
            "Regional State and Local Affairs Lead, Western States",
            "Research Economist, Economic Research",
            "Anthropic AI Safety Fellow",
            "Anthropic AI Security Fellow",
            "Applied Safety Research Engineer, Safeguards",
            "Certification Content and Systems Architect",
            "Data Operations Manager, Computer Use & Tool Use",
            "Engineering Manager, Inference",
            "Engineering Manager, ML Acceleration",
            "[Expression of Interest] Research Manager, Interpretability",
            "[Expression of Interest] Research Scientist/Engineer, Alignment Finetuning",
            "[Expression of Interest] Research Scientist/Engineer, Honesty",
            "Founding Design Engineer, AI Capability Development, Education Labs",
            "Full Stack Software Engineer, Reinforcement Learning",
            "Machine Learning Systems Engineer, Research Tools",
            "Machine Learning Systems Engineer, RL Engineering",
            "ML Infrastructure Engineer, Safeguards",
            "ML/Research Engineer, Safeguards",
            "Performance Engineer",
            "Performance Engineer, GPU",
            "Privacy Research Engineer, Safeguards",
            "Research Engineer – Cybersecurity RL",
            "Research Engineer, Discovery",
            "Research Engineer, Frontier Red Team (Autonomy)",
            "Research Engineer, Frontier Red Team (Hardware Lead)",
            "Research Engineer, Interpretability",
            "Research Engineer, Machine Learning (Reinforcement Learning)",
            "Research Engineer, Model Evaluations",
            "Research Engineer, Pre-training",
            "Research Engineer, Pretraining Scaling",
            "Research Engineer, Production Model Post Training",
            "Research Engineer, Production Model Post-Training - London",
            "Research Engineer/Research Scientist, Audio",
            "Research Engineer / Research Scientist, Biology & Life Sciences",
            "Research Engineer / Research Scientist, Pre-training",
            "Research Engineer / Research Scientist, Vision",
            "Research Engineer, Reward Models Platform",
            "Research Engineer, Reward Models Training",
            "Research Engineer / Scientist, Alignment Science",
            "Research Engineer / Scientist, Alignment Science, London",
            "Research Engineer / Scientist, Frontier Red Team (Cyber)",
            "Plus 327+ more positions across various teams"
        ]
    },
    {
        name: "Replit",
        website: "https://jobs.ashbyhq.com/replit",
        jobs: [
            "Agent Platform Engineer",
            "Associate Financial Analyst",
            "Brand Copy Lead",
            "Brand Design Lead",
            "Cloud Security Lead",
            "Commercial Account Executive",
            "Commercial Account Manager",
            "Corporate Accountant",
            "Data Engineer",
            "Data Engineer, Financial Systems",
            "Data Scientist, AI Agent",
            "Data Scientist, Marketing",
            "Design Engineer",
            "Engineering Director, Replit Cloud",
            "Engineering Manager, Enterprise Platform",
            "Engineering Manager, Mobile",
            "Enterprise Account Executive",
            "Enterprise Account Manager",
            "Executive Assistant to CRO & CMO",
            "Field Engineer",
            "Growth Product Manager",
            "Payroll Manager",
            "Premium Support Engineer",
            "Principal Software Engineer, Money Infrastructure",
            "Product Designer, B2B",
            "Product Marketing Manager",
            "Product Security Engineer (PSIRT)",
            "SDR",
            "Security Operations Lead",
            "Senior Infrastructure Engineer",
            "Senior Manager, Sales Development",
            "Senior Partner Marketing Manager",
            "Senior Product Manager",
            "Senior Software Engineer, Anti-Abuse & Security",
            "Senior Software Engineer, Money",
            "Senior Staff Software Engineer, Replit Cloud",
            "Senior Support Manager",
            "Site Reliability Engineer",
            "SOC Engineer",
            "Software Engineer, Compute Platform",
            "Software Engineer, Demand Gen",
            "Software Engineer, Enterprise",
            "Software Engineer, Growth",
            "Software Engineer, Growth Infrastructure",
            "Software Engineering Intern (Summer 2026)",
            "Software Engineer - New Grad (Summer 2026)",
            "Software Engineer, Product Infrastructure (TypeScript DevEx)",
            "Software Engineer, Replit Cloud",
            "Sr. Director, Talent Acquisition",
            "Staff Infrastructure Engineer",
            "Staff Product Designer, B2B",
            "Staff Product Designer, Design System",
            "Staff Site Reliability Engineer",
            "Staff Software Engineer, Money",
            "Staff Software Engineer, Product",
            "Support Engineer I"
        ]
    },
    {
        name: "Freepik",
        website: "https://www.freepik.com/jobs",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "ElevenLabs",
        website: "https://jobs.ashbyhq.com/elevenlabs",
        jobs: [
            "Account Executive - Government and Public Sector - Central Europe",
            "Account Executive - Government and Public Sector - Spain",
            "Account Executive - Government and Public Sector - UK/I",
            "Account Executive - India",
            "Account Executive - Japan",
            "Account Executive - LATAM",
            "Account Executive - Middle East",
            "Account Executive - Southeast Asia",
            "Commercial Account Executive - United States",
            "Enterprise Account Executive - United States",
            "Enterprise Account Executive - United States - Government",
            "Enterprise Account Executive - United States - Healthcare",
            "Customer Enablement - United States",
            "Customer Success - EMEA - Nordics",
            "Customer Success - EMEA - Scale",
            "Customer Success - EMEA - Southern Europe",
            "Customer Success - EMEA - Strategic",
            "Customer Success - EMEA - Western Europe",
            "Customer Success - India - Scale",
            "Customer Success - LATAM",
            "Customer Success - Middle East",
            "Customer Success - North America - Corporate",
            "Customer Success - North America - Enterprise",
            "Customer Success - North America - Strategic",
            "Customer Success Strategy and Operations",
            "Customer Success - United States - Mid-Market",
            "Customer Success Lead - UK/I",
            "Customer Success Lead - Western Europe",
            "AI Safety Policy & Operations",
            "Android Engineer",
            "Audiobook Specialists - Freelance",
            "Automations Engineer",
            "Design Engineer",
            "Deployment Strategist",
            "Enterprise Solutions Engineer",
            "Enterprise Solutions Engineer - EU (French Speaking)",
            "Dubbing Specialist - Freelance",
            "AI Creative Producer",
            "B2B Growth Marketing - Agents",
            "B2B Marketing - Korea",
            "B2B Performance Marketer - Media Buyer",
            "Brand Design",
            "Consumer Music Marketing Lead",
            "Data Scientist - Marketing",
            "Developer Marketing Lead",
            "Developer Relations Engineer",
            "Commercial Counsel - U.S.",
            "Customer Support Specialist"
        ]
    },
    {
        name: "Cursor",
        website: "https://cursor.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Flyver.ai",
        website: "https://flyver.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Lorileet",
        website: "https://lorileet.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "micro1",
        website: "https://micro1.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Notion",
        website: "https://www.notion.com/careers",
        jobs: [
            "Account Executive - Commercial",
            "Account Executive - Enterprise",
            "Account Executive - Mid-Market",
            "Commercial Sales Manager",
            "Enterprise Account Executive",
            "Sales Development Representative",
            "Sales Engineering Manager",
            "Solutions Engineer",
            "Solutions Engineering Manager",
            "Technical Architect",
            "Software Engineer - Cloud Infrastructure",
            "Software Engineer - Datastore",
            "Software Engineer - Mail",
            "Software Engineer - Product Platform",
            "Data Engineer",
            "QA Engineer",
            "Engineering Manager - AI Search",
            "Engineering Manager - Developer Platform",
            "AI Applications Engineer",
            "Staff Software Engineer",
            "Customer Success Manager",
            "Enterprise Customer Success Manager",
            "Scaled Customer Success Manager",
            "Customer Experience Enablement Leader",
            "Support Specialist",
            "Solutions Consultant",
            "Business Development Representative",
            "Sales Development Manager",
            "Corporate Finance",
            "Revenue Accountant",
            "Head of Business Partnership Finance",
            "Head of Internal Audit",
            "Strategic Finance",
            "Product Marketing Manager",
            "Enterprise Product Marketing",
            "Creative Studio Operations Manager",
            "Event Marketing",
            "Business Recruiter",
            "GTM Recruiter",
            "Recruiting Coordinator",
            "Talent Sourcer",
            "Global Head of GTM Recruiting",
            "Head of People Analytics",
            "Business Systems Analyst",
            "Business Systems Architect",
            "Business Systems Engineer",
            "Corporate Infrastructure Engineer",
            "Security Operations Engineer",
            "Workplace Coordinator",
            "Workplace Lead",
            "Head of Internal Communications",
            "Software Engineer Intern (Summer 2026)",
            "UX Research Intern (Summer 2026)"
        ]
    },
    {
        name: "Delve",
        website: "https://www.delve.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Perplexity",
        website: "https://jobs.ashbyhq.com/perplexity",
        jobs: [
            "Accounting Manager",
            "AI Engineer, Applied ML",
            "AI Inference Engineer",
            "AI Infra Engineer",
            "AI Researcher",
            "AI Research Lead",
            "AI Security Engineer",
            "AI Software Engineer - Comet Agents",
            "Analytics Engineer",
            "Android Engineer - Comet",
            "Application Security Engineer",
            "Applied AI Engineer - Full Stack",
            "Backend Software Engineer",
            "Backend Software Engineer - Mobile",
            "Backend Software Engineer - Search, Crawler Team",
            "Browser C++ Engineer",
            "Browser Infrastructure Engineer",
            "Browser QA Engineer",
            "Browser Security Engineer",
            "Business Development Representative",
            "Cloud Security Engineer",
            "Content Manager - Enterprise",
            "Customer Success Associate (Comet Browser)",
            "Customer Success Engineer (APAC, Remote)",
            "Customer Support and Success Associate APAC",
            "Data Scientist - Growth",
            "Data Scientist - Product",
            "Engineering Manager - Inference",
            "Engineering Site Lead",
            "Enterprise Customer Success Manager",
            "Enterprise Growth Lead",
            "Executive Communications Manager",
            "Forward-Deployed Engineer - API Platform",
            "Frontend Engineer - Design Systems",
            "Frontend Software Engineer",
            "Full Stack Software Engineer",
            "Governance, Risk & Compliance Lead",
            "Internship - Machine Learning Research Engineer",
            "Internship - Search Backend Infra Engineer",
            "Internship - Search Machine Learning Engineer",
            "iOS Growth Engineer",
            "IT Systems Administrator",
            "IT Systems Administrator (Serbia)",
            "Model Behavior Architect",
            "Product Data Scientist, Search Quality",
            "Product Marketing Manager",
            "Product Quality Assurance Architect",
            "Research & Development Accounting Manager",
            "Search DevOps Engineer",
            "Search Full Stack Engineer",
            "Search Golang Engineer",
            "Search Machine Learning Research Engineer",
            "Search Rust Engineer",
            "Search Senior Backend/Infrastructure Engineer",
            "Search Senior Machine Learning Engineer",
            "Senior C++ Developer - Search Core",
            "Senior iOS Software Engineer",
            "Senior/Staff Software Engineer - Data Platform",
            "Senior/Staff Software Engineer - Infrastructure",
            "Senior/Staff Web Platform Engineer",
            "Software Engineer - Acceleration",
            "Software Engineer - Agent Infra",
            "Software Engineer, AI Platform",
            "Software Engineer - Security",
            "Solutions Engineering Lead",
            "Staff Backend Software Engineer - API Platform",
            "Strategic Finance Lead - Core",
            "Strategic Finance Lead - GTM",
            "Tech Lead Manager - Agents"
        ]
    },
    {
        name: "Instantly",
        website: "https://instantly.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Customer.io",
        website: "https://customer.io/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "KlingAI",
        website: "https://klingai.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Retell AI",
        website: "https://www.retellai.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Canva",
        website: "https://www.canva.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Lovable",
        website: "https://jobs.ashbyhq.com/lovable",
        jobs: [
            "AI Engineer",
            "Backend Product Engineer",
            "Data Platform Engineer",
            "Analytics Engineer",
            "Application Security Engineer",
            "Forward Deployed Engineer",
            "Fullstack Engineer - Security",
            "Fullstack Growth Engineer",
            "Fullstack Product Engineer",
            "FullStack Engineering Lead - Security",
            "Platform Engineer - Developer Experience",
            "Platform Engineer - Infrastructure",
            "Security Engineer",
            "Brand Designer",
            "Design Engineer",
            "Design Engineer (Web & Brand)",
            "Motion Designer",
            "Product Designer",
            "Data Scientist",
            "Product Manager",
            "Product Experience Specialist (APAC)",
            "Product Experience Specialist (Sweden)",
            "UX Researcher",
            "Customer Success Manager",
            "Deployment Strategist",
            "Enterprise Account Executive",
            "Enterprise Deal Desk Lead",
            "Enterprise Hackathon Director",
            "Enterprise Technical Support Engineer",
            "Solutions Architect",
            "Customer Education Lead",
            "GTM Operations - Systems and Automation",
            "GTM Partnership Operations",
            "Head of Channels & Partnerships",
            "Head of Sales (North America)",
            "B2B Lifecycle Marketing Manager",
            "External Communications Lead (Europe)",
            "External Communications Lead (US)",
            "Field Marketing Lead – Enterprise",
            "Head of Community Marketing",
            "Head of Customer Marketing",
            "Integrated Marketing Lead",
            "Internal Communications Lead",
            "Lifecycle Marketing Lead",
            "Marketing Analyst",
            "Partner Marketing Lead",
            "Technical Evangelist",
            "AI Ops Engineer - Finance",
            "Finance & BizOps - EPD",
            "Finance & BizOps - GTM",
            "Revenue Systems & Accounting Lead",
            "Senior Financial Accountant",
            "GTM Recruiter",
            "HR Business Partner GTM",
            "People Operations Manager",
            "Recruitment Coordinator",
            "Technical Recruiter",
            "Workplace Manager"
        ]
    },
    {
        name: "Metaview",
        website: "https://jobs.ashbyhq.com/metaview",
        jobs: [
            "Account Executive, Enterprise",
            "Account Executive, Mid Market",
            "Account Executive, SMB",
            "Business Analytics",
            "Chief of Staff",
            "Director of Sales, EMEA",
            "Engagement Associate",
            "Engagement Manager",
            "Finance Operations",
            "Growth Marketing Manager",
            "GTM Recruiter",
            "Product Designer",
            "Product Engineer (Backend-biased)",
            "Product Engineer (Frontend-biased)",
            "Product Marketing Manager",
            "Revenue Operations",
            "Sales Development Representative",
            "Technical Recruiter",
            "Technical Support Engineer"
        ]
    },
    {
        name: "ADEPT",
        website: "https://www.adept.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Glean",
        website: "https://glean.com/careers",
        jobs: [
            "AI Outcomes Manager",
            "Delivery Excellence Manager",
            "Forward Deployed Product Manager",
            "Founding Forward Deployed Engineer",
            "Manager AI Outcomes",
            "Manager Delivery Excellence",
            "Software Engineer Consulting Services",
            "Solutions Architect",
            "Senior/Staff Applied Scientist",
            "Tech Lead Manager Data Engineering",
            "Product Designer",
            "Product Design Lead AI Products",
            "Application Security Engineer",
            "Cloud Infrastructure Engineer",
            "Cloud Security Engineer",
            "Lead Software Engineer Product Backend",
            "Machine Learning Engineer AI Assistant + Autonomous AI Agents",
            "Machine Learning Engineer Enterprise Brain",
            "Machine Learning Engineer Infrastructure",
            "Machine Learning Engineer Search Quality",
            "Security Engineer",
            "Security Engineer Application Security",
            "Security Engineer Cloud Security",
            "Software Engineer Agentic Runtime",
            "Software Engineer AI and Security",
            "Software Engineer Backend",
            "Software Engineer Data Foundations",
            "Software Engineer Developer Platform",
            "Software Engineer Developer Productivity",
            "Software Engineer Frontend",
            "Software Engineer Fullstack",
            "Software Engineer Machine Learning",
            "Software Engineer Platform",
            "Software Engineer Product Backend",
            "Software Engineer Security",
            "Tech Lead Manager",
            "Technical Lead Billing and Revenue Platform",
            "Tech Lead Manager Billing and Insights",
            "Finance Systems Trainee",
            "Global Mobility and Operations Specialist",
            "Head of Human Resources",
            "HR Business Partner",
            "Office Manager",
            "People Analytics Lead",
            "Recruiting Coordinator",
            "Sales Compensation Director",
            "Senior Payroll Analyst",
            "Senior Tax Analyst",
            "Strategic Finance Lead",
            "Talent Sourcer",
            "Technical Recruiter",
            "Total Rewards Manager",
            "Customer Reference Specialist",
            "Field Marketing Programs Manager",
            "Senior Partner Marketing Manager",
            "Technical Marketing Engineer",
            "Product Management Lead",
            "Product Manager",
            "Product Manager Admin and Enterprise Platform",
            "Product Manager Agent Security and Governance",
            "Product Manager AI Quality",
            "Product Manager Connectors",
            "Product Manager Glean Protect",
            "Product Operations",
            "Senior Security Technical Program Manager",
            "Senior Technical Program Manager",
            "Senior Technical Writer",
            "Technical Writer",
            "Lead Quality Assurance",
            "Quality Assurance Engineer",
            "Quality Assurance Manager",
            "Account Executive",
            "Business Development Representative",
            "Channel Partner Manager",
            "Solutions Engineer",
            "Sales Development Representative",
            "Strategic Account Executive",
            "Designated Technical Support Engineer",
            "Technical Support Engineer",
            "Software Engineer University Grad"
        ]
    },
    {
        name: "Photoroom",
        website: "https://jobs.ashbyhq.com/photoroom",
        jobs: [
            "Account Based Marketing & Events Lead",
            "Head of Computer Vision",
            "Head of Cross-Platform (Rust)",
            "Head of Cross-Platform SDK (Rust)",
            "Head of Monetization & Growth",
            "Head of Real-Time & Editing Engine (Rust)",
            "Senior Frontend Engineer, Web",
            "Senior SEO & GEO/AEO Strategist",
            "Solutions Engineer (EMEA)"
        ]
    },
    {
        name: "Solve Intelligence",
        website: "https://www.solveintelligence.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Gamma",
        website: "https://gamma.app/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Clay",
        website: "https://www.clay.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Cluely",
        website: "https://cluely.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Crosby",
        website: "https://www.crosby.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Midjourney",
        website: "https://www.midjourney.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Combinely",
        website: "https://combinely.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Merlin",
        website: "https://www.getmerlin.in/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Descript",
        website: "https://www.descript.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Grammarly",
        website: "https://www.grammarly.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Manus",
        website: "https://www.manus.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Cognition",
        website: "https://jobs.ashbyhq.com/cognition",
        jobs: [
            "AI Enablement Engineer",
            "Analytics Engineer",
            "Business Operations",
            "Data Engineer",
            "Delta Engineer",
            "Delta Engineer - Federal",
            "Delta Engineer - UK",
            "Deployed Engineer",
            "Deployed Engineer - UK",
            "Engagement Manager",
            "Enterprise Narrative",
            "Federal Account Executive",
            "Federal Civilian GTM Leader",
            "Field Marketer",
            "Founding Country Leader - Japan",
            "General Application",
            "GTM Manager",
            "GTM Manager - Enterprise",
            "GTM Manager - UK",
            "Integrated Campaigns Manager",
            "International Field CTO",
            "IT Engineer",
            "Machine Learning Researcher",
            "Partner Deployed Engineer - India",
            "Partner Marketer",
            "Product Engineer",
            "Revenue Operations",
            "Sales Development Representative",
            "Software Engineer",
            "Special Projects Engineer",
            "Special Projects Engineer - UK"
        ]
    },
    {
        name: "OpusClip",
        website: "https://www.opus.pro/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Happyscribe",
        website: "https://www.happyscribe.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "11x",
        website: "https://11x.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "PLAUD",
        website: "https://www.plaud.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Serval",
        website: "https://www.serval.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Ada",
        website: "https://www.ada.cx/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Otter.ai",
        website: "https://job-boards.greenhouse.io/otter",
        jobs: [
            "Software Engineer - Streaming Data, Otter - Seattle",
            "Software Engineer - Android Mobile, Otter - Los Angeles",
            "Staff Software Engineer - Android Mobile, Otter - Los Angeles",
            "Backend Engineer, Otter - Mountain View, CA",
            "Backend Software Engineer, Otter - Los Angeles",
            "Software Engineer, Menu & POS Platform, Otter - Mountain View",
            "Staff Software Engineer, Menu & POS Platform, Otter - Mountain View, CA",
            "Staff Software Engineer (Money Engineering), Otter - New York City",
            "Senior Staff Software Engineer, Otter - São Paulo",
            "Sales Operations Manager, Otter - Los Angeles",
            "Sales Development Representative, Otter - Mexico",
            "Strategic Enterprise Account Executive, Otter - Los Angeles",
            "Customer Onboarding Coordinator, Otter - London",
            "Customer Success Associate, Otter - Los Angeles",
            "Product Design Lead, Otter/Menu - Mountain View",
            "Product Manager Growth, Otter - San Francisco",
            "Product Manager, Otter - Los Angeles",
            "Product Manager - Data Products, Otter - Seattle",
            "Group Product Manager, Otter - Mountain View"
        ]
    },
    {
        name: "Alma",
        website: "https://www.alma.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Apploud",
        website: "https://www.apploud.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "CapCut",
        website: "https://www.capcut.com/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Motion",
        website: "https://jobs.ashbyhq.com/motion",
        jobs: [
            "Customer Support Representative (AR)",
            "Customer Support Representative (CH)",
            "Customer Support Representative (CO)",
            "Customer Support Representative (EE)",
            "Customer Support Representative (GA)",
            "Customer Support Representative (IE)",
            "Customer Support Representative (PH)",
            "Customer Support Representative (PL)",
            "Customer Support Representative (RO)",
            "Customer Support Representative (UA)",
            "Engineering Manager",
            "Principal Software Engineer",
            "Principal Software Engineer (SF-based)",
            "Senior Electron App Engineer",
            "Senior Staff Frontend Engineer"
        ]
    },
    {
        name: "Crisp",
        website: "https://crisp.chat/en/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Arcads",
        website: "https://www.arcads.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Emergent",
        website: "https://www.emergent.ai/careers",
        jobs: ["Career page to be accessed"]
    },
    {
        name: "Read AI",
        website: "https://jobs.ashbyhq.com/read-ai",
        jobs: [
            "Account Coordinator",
            "Backend Engineer",
            "Backend Engineer - Enterprise Applications",
            "Director of Growth Marketing",
            "Director of People",
            "Growth Product Manager",
            "Product Designer",
            "Senior Product Manager",
            "Senior Software Engineer - Backend",
            "Senior Software Engineer - Data",
            "Senior Software Engineer - Frontend",
            "Senior Software Engineer - Mobile",
            "Software Engineering Manager - Frontend",
            "Software Engineer - Mobile",
            "VP of Marketing"
        ]
    },
    {
        name: "Tavus",
        website: "https://www.tavus.io/careers",
        jobs: ["Career page to be accessed"]
    }
];
